### ISSUE TITLE
What exactly needs that data appears in the access_token template variable?

### ISSUE THREAD

**Issue by ewwmy** [jdinicola/insomnia-plugin-get-access-token#1]
@jdinicola, hello and thank you for this plugin :) But I have a problem with it.

As far as I understand, I need to create a header with the name `JSONPath-filter` and value `$.data.access_token` (in my case) in the authorization request. I did this way but it didn't work for me. `access_token` variable is empty.

I think a more detailed instruction with a screenshot of creating a filter would be very helpful.

**Comment by jdinicola** [comment]
Hi @andryx77 

Yes, that's the header you need... Could you provide an example response to make sure the filter is right?

Are you clicking on the "Authorize requests" button on the authorization request itself before trying to read access_token?

**Comment by ewwmy** [comment]
Hi, @jdinicola!

My auth response is (provided token is just for example):

```json
{
  "answer": "OK",
  "uri": "/api/auth/login",
  "data": {
    "access_token": "lkfjsdlkgdgldngdgdfgfdg",
    "user": {
      "id": 1,
      "email": "admin@example.com",
      "role": {
        "id": 1,
        "name": "admin"
      }
    }
  }
}
```

And I use the following header in my auth request:
`JSONPath-filter`: `$.data.access_token`

Is this correct?

Then I click on the "Authorize requests" button, but the `access_token` template variable is still empty (has `0` value and Live preview returns the `error`).

My Insomnia version is:
```text
Version: Insomnia 2021.4.1
Release date: 7/7/2021
OS: Darwin x64 20.6.0
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```

Thanks!

**Comment by jdinicola** [comment]
Hi @andryx77 

I've been testing with that exact version of Insomnia, your example auth response and your filter and everything works fine...

Maybe it's a permissions issue on your machine. You see, this plugin uses Insomnia's storage context to store the data (the template variable). As far as I know, this data is saved on ~/Library/Application\ Support/Insomnia/insomnia.PluginData.db file.

Can you check that this file, or the entire directory are writable?

Also, can you enable DevTools on Insomnia app and check if there's an error on the console that may help us.

Thank you

**Comment by its-james** [comment]
Hey, I would make sure that the API responds with code 200, or change it in the code to fit your needs :)

**Comment by ewwmy** [comment]
Hi! Ok, I've been checked developer console and it looks like clean.

And I've also been changed the response code to 200 for my auth request. Now it's working. Thanks! But you could make your plugin more flexible for that it covers any success codes, not only 200. 🙂

**Comment by jdinicola** [comment]
Hi,

I just published a new version of the plugin in which I added the HTTP status code 201.

I think that the only HTTP status codes that make sense to allow are **200 OK** and **201 Accepted** because are the only success codes that returns data.

Thank you for using the plugin 🙂
