### ISSUE TITLE
Get token from response header

### ISSUE THREAD

**Issue by nathani-work** [jdinicola/insomnia-plugin-get-access-token#4]
Hey, I love the plugin, I've been looking for something like it for a while.

I have a token that is returned in the response headers, with no body. How difficult would it be to catch the header from it ?

I might do it myself if I have some time and understand the code.

**Comment by jdinicola** [comment]
Hi @nathani-axis 

I just published a new version with the option to get the token from a response header.

Now, you can add the TokenResponseHeader request header with the name of the response header that contains the token, to get it from there.

Thank you for using the plugin.
